import { Pool } from 'pg';
import { hash } from 'bcryptjs';

const DATABASE_URL = process.env.DATABASE_URL || 'postgresql://noa:noa@localhost:5432/brainstack';

const pool = new Pool({ connectionString: DATABASE_URL });

// ── Helpers ──────────────────────────────────────────────────────────────────

function slugify(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function splitIntoChunks(mdx: string): { heading: string; content: string }[] {
  const sections: { heading: string; content: string }[] = [];
  const lines = mdx.split('\n');
  let currentHeading = 'Introduction';
  let currentContent: string[] = [];

  for (const line of lines) {
    const headingMatch = line.match(/^#{2,3}\s+(.+)/);
    if (headingMatch) {
      if (currentContent.length > 0) {
        const text = currentContent.join('\n').trim();
        if (text) sections.push({ heading: currentHeading, content: text });
      }
      currentHeading = headingMatch[1];
      currentContent = [];
    } else {
      currentContent.push(line);
    }
  }
  if (currentContent.length > 0) {
    const text = currentContent.join('\n').trim();
    if (text) sections.push({ heading: currentHeading, content: text });
  }
  return sections;
}

function stripMdx(text: string): string {
  return text
    .replace(/```[\s\S]*?```/g, '')
    .replace(/`[^`]+`/g, '')
    .replace(/#{1,6}\s+/g, '')
    .replace(/[*_~\[\]()]/g, '')
    .replace(/\n{2,}/g, '\n')
    .trim();
}

// Use $ + {} to produce literal ${} in strings without template literal interpolation
const D = '$';

// ── Collections ──────────────────────────────────────────────────────────────

const collections = [
  { name: 'DevOps',   slug: 'devops',   description: 'Infrastructure, CI/CD, and deployment',   icon: '🔧', color: '#3B82F6' },
  { name: 'Frontend', slug: 'frontend', description: 'UI frameworks, styling, and browser APIs', icon: '🎨', color: '#8B5CF6' },
  { name: 'Backend',  slug: 'backend',  description: 'Server-side development and APIs',        icon: '⚙️', color: '#10B981' },
  { name: 'Database', slug: 'database', description: 'SQL, NoSQL, and data modeling',            icon: '🗄️', color: '#F59E0B' },
  { name: 'Security', slug: 'security', description: 'Application security and best practices',  icon: '🔒', color: '#EF4444' },
  { name: 'AI/ML',    slug: 'ai-ml',    description: 'Machine learning and AI engineering',      icon: '🤖', color: '#EC4899' },
];

// ── Pages ────────────────────────────────────────────────────────────────────

interface PageDef {
  title: string;
  type: 'tutorial' | 'tip' | 'cheatsheet' | 'note';
  collection: string;
  summary: string;
  tags: string[];
  mdx: string;
}

const pages: PageDef[] = [
  // ── DevOps ─────────────────────────────────────────────────────────────────
  {
    title: 'Getting Started with Docker Compose',
    type: 'tutorial',
    collection: 'devops',
    summary: 'Learn how to define and run multi-container applications with Docker Compose.',
    tags: ['docker', 'containers', 'devops', 'compose'],
    mdx: [
      '## Why Docker Compose?',
      '',
      'Docker Compose lets you define multi-container applications in a single YAML file. Instead of running multiple `docker run` commands with complex flags, you declare your entire stack declaratively. This is essential for local development environments that mirror production.',
      '',
      'Compose handles networking between containers automatically, manages volume mounts, and provides a single command to bring your entire stack up or down. It\'s the bridge between "it works on my machine" and reproducible environments.',
      '',
      '## Writing Your First docker-compose.yml',
      '',
      'Create a `docker-compose.yml` at your project root:',
      '',
      '```yaml',
      "version: '3.8'",
      '',
      'services:',
      '  app:',
      '    build: .',
      '    ports:',
      '      - "3000:3000"',
      '    environment:',
      '      DATABASE_URL: postgresql://user:pass@db:5432/myapp',
      '    depends_on:',
      '      db:',
      '        condition: service_healthy',
      '',
      '  db:',
      '    image: postgres:16',
      '    environment:',
      '      POSTGRES_USER: user',
      '      POSTGRES_PASSWORD: pass',
      '      POSTGRES_DB: myapp',
      '    volumes:',
      '      - pgdata:/var/lib/postgresql/data',
      '    healthcheck:',
      '      test: ["CMD-SHELL", "pg_isready -U user"]',
      '      interval: 5s',
      '      timeout: 5s',
      '      retries: 5',
      '',
      'volumes:',
      '  pgdata:',
      '```',
      '',
      'The `depends_on` with `condition: service_healthy` ensures your app waits for Postgres to be ready, not just started. This prevents connection errors during startup.',
      '',
      '## Essential Commands',
      '',
      '```bash',
      '# Start all services in the background',
      'docker compose up -d',
      '',
      '# View logs from all services',
      'docker compose logs -f',
      '',
      '# Rebuild after Dockerfile changes',
      'docker compose up -d --build',
      '',
      '# Stop and remove containers, networks',
      'docker compose down',
      '',
      '# Stop and remove everything including volumes',
      'docker compose down -v',
      '```',
      '',
      '## Environment Variables and Overrides',
      '',
      'Use a `.env` file for variable substitution in your compose file:',
      '',
      '```bash',
      '# .env',
      'POSTGRES_VERSION=16',
      'APP_PORT=3000',
      '```',
      '',
      '```yaml',
      'services:',
      '  db:',
      '    image: postgres:' + D + '{POSTGRES_VERSION}',
      '  app:',
      '    ports:',
      '      - "' + D + '{APP_PORT}:3000"',
      '```',
      '',
      'For local overrides, create `docker-compose.override.yml`. Compose merges it automatically, so you can add debug ports or mount source code without touching the base file.',
      '',
      '### Multi-Stage Builds',
      '',
      'Combine Compose with multi-stage Dockerfiles for optimal images:',
      '',
      '```dockerfile',
      'FROM node:20-alpine AS builder',
      'WORKDIR /app',
      'COPY package*.json ./',
      'RUN npm ci',
      'COPY . .',
      'RUN npm run build',
      '',
      'FROM node:20-alpine AS runner',
      'WORKDIR /app',
      'COPY --from=builder /app/dist ./dist',
      'COPY --from=builder /app/node_modules ./node_modules',
      'CMD ["node", "dist/index.js"]',
      '```',
      '',
      'This keeps your production image lean while still having all build tools available during the build stage.',
    ].join('\n'),
  },
  {
    title: 'Building REST APIs with Next.js App Router',
    type: 'tutorial',
    collection: 'backend',
    summary: 'Create type-safe REST APIs using Next.js route handlers and Zod validation.',
    tags: ['nextjs', 'api', 'rest', 'typescript', 'zod'],
    mdx: [
      '## Route Handlers in the App Router',
      '',
      'Next.js App Router uses file-based routing for API endpoints. Create a `route.ts` file inside any folder under `app/api/` and export named functions matching HTTP methods.',
      '',
      '```typescript',
      '// app/api/posts/route.ts',
      "import { NextRequest, NextResponse } from 'next/server';",
      '',
      'export async function GET(request: NextRequest) {',
      '  const { searchParams } = new URL(request.url);',
      "  const page = parseInt(searchParams.get('page') || '1');",
      "  const limit = parseInt(searchParams.get('limit') || '20');",
      '',
      '  const posts = await db.query.posts.findMany({',
      '    offset: (page - 1) * limit,',
      '    limit,',
      '    orderBy: (posts, { desc }) => [desc(posts.createdAt)],',
      '  });',
      '',
      '  return NextResponse.json({ data: posts, page, limit });',
      '}',
      '```',
      '',
      '## Request Validation with Zod',
      '',
      'Never trust client input. Use Zod schemas to validate request bodies and query parameters:',
      '',
      '```typescript',
      "import { z } from 'zod';",
      '',
      'const CreatePostSchema = z.object({',
      '  title: z.string().min(1).max(200),',
      '  content: z.string().min(10),',
      "  status: z.enum(['draft', 'published']).default('draft'),",
      '  tags: z.array(z.string()).max(10).optional(),',
      '});',
      '',
      'export async function POST(request: NextRequest) {',
      '  const body = await request.json();',
      '  const result = CreatePostSchema.safeParse(body);',
      '',
      '  if (!result.success) {',
      '    return NextResponse.json(',
      "      { error: 'Validation failed', details: result.error.flatten() },",
      '      { status: 400 }',
      '    );',
      '  }',
      '',
      '  const post = await db.insert(posts).values(result.data).returning();',
      '  return NextResponse.json({ data: post[0] }, { status: 201 });',
      '}',
      '```',
      '',
      '## Dynamic Route Segments',
      '',
      'Handle individual resources with dynamic segments:',
      '',
      '```typescript',
      '// app/api/posts/[id]/route.ts',
      'export async function GET(',
      '  request: NextRequest,',
      '  { params }: { params: Promise<{ id: string }> }',
      ') {',
      '  const { id } = await params;',
      '  const post = await db.query.posts.findFirst({',
      '    where: (posts, { eq }) => eq(posts.id, id),',
      '  });',
      '',
      '  if (!post) {',
      "    return NextResponse.json({ error: 'Not found' }, { status: 404 });",
      '  }',
      '',
      '  return NextResponse.json({ data: post });',
      '}',
      '',
      'export async function PATCH(',
      '  request: NextRequest,',
      '  { params }: { params: Promise<{ id: string }> }',
      ') {',
      '  const { id } = await params;',
      '  const body = await request.json();',
      '  const result = UpdatePostSchema.safeParse(body);',
      '',
      '  if (!result.success) {',
      '    return NextResponse.json(',
      "      { error: 'Validation failed', details: result.error.flatten() },",
      '      { status: 400 }',
      '    );',
      '  }',
      '',
      '  const updated = await db',
      '    .update(posts)',
      '    .set({ ...result.data, updatedAt: new Date() })',
      '    .where(eq(posts.id, id))',
      '    .returning();',
      '',
      '  return NextResponse.json({ data: updated[0] });',
      '}',
      '```',
      '',
      '### Error Handling Middleware Pattern',
      '',
      'Wrap handlers in a utility to catch errors consistently:',
      '',
      '```typescript',
      'type Handler = (req: NextRequest, ctx: any) => Promise<NextResponse>;',
      '',
      'function withErrorHandler(handler: Handler): Handler {',
      '  return async (req, ctx) => {',
      '    try {',
      '      return await handler(req, ctx);',
      '    } catch (error) {',
      "      console.error('API Error:', error);",
      '      return NextResponse.json(',
      "        { error: 'Internal server error' },",
      '        { status: 500 }',
      '      );',
      '    }',
      '  };',
      '}',
      '```',
      '',
      'This pattern keeps your route handlers clean and ensures no unhandled promise rejections leak to the client.',
    ].join('\n'),
  },
  {
    title: 'Git Commands Cheatsheet',
    type: 'cheatsheet',
    collection: 'devops',
    summary: 'Essential Git commands for daily development workflows.',
    tags: ['git', 'version-control', 'devops', 'cheatsheet'],
    mdx: [
      '## Setup and Configuration',
      '',
      '```bash',
      '# Set identity',
      'git config --global user.name "Your Name"',
      'git config --global user.email "you@example.com"',
      '',
      '# Useful aliases',
      'git config --global alias.co checkout',
      'git config --global alias.br branch',
      'git config --global alias.st status',
      'git config --global alias.lg "log --oneline --graph --all"',
      '',
      '# Default branch name',
      'git config --global init.defaultBranch main',
      '```',
      '',
      '## Daily Workflow',
      '',
      '```bash',
      '# Check status',
      'git status',
      'git diff                    # Unstaged changes',
      'git diff --staged           # Staged changes',
      '',
      '# Stage and commit',
      'git add -p                  # Interactive staging (patch mode)',
      'git commit -m "feat: add user auth"',
      'git commit --amend          # Fix last commit message',
      '',
      '# Branching',
      'git checkout -b feature/auth',
      'git switch -c feature/auth  # Modern alternative',
      'git branch -d feature/auth  # Delete merged branch',
      'git branch -D feature/auth  # Force delete',
      '```',
      '',
      '## History and Inspection',
      '',
      '```bash',
      '# View history',
      'git log --oneline -20',
      'git log --graph --all --oneline',
      'git log --author="name" --since="2 weeks ago"',
      '',
      '# Find who changed a line',
      'git blame src/auth.ts',
      'git blame -L 10,20 src/auth.ts  # Specific lines',
      '',
      '# Search commits',
      'git log --grep="fix auth"',
      'git log -S "functionName"   # Find when code was added/removed',
      '```',
      '',
      '## Undoing Changes',
      '',
      '```bash',
      '# Unstage files',
      'git restore --staged file.ts',
      'git reset HEAD file.ts      # Older syntax',
      '',
      '# Discard working changes',
      'git restore file.ts',
      'git checkout -- file.ts     # Older syntax',
      '',
      '# Undo last commit (keep changes)',
      'git reset --soft HEAD~1',
      '',
      '# Undo last commit (discard changes)',
      'git reset --hard HEAD~1',
      '',
      '# Create a revert commit',
      'git revert abc123',
      '```',
      '',
      '## Stashing',
      '',
      '```bash',
      'git stash                   # Stash working changes',
      'git stash -u                # Include untracked files',
      'git stash list              # View stash stack',
      'git stash pop               # Apply and remove top stash',
      'git stash apply stash@{2}   # Apply specific stash',
      'git stash drop stash@{0}    # Remove specific stash',
      '```',
      '',
      '## Remote Operations',
      '',
      '```bash',
      '# Fetch and pull',
      'git fetch origin',
      'git pull --rebase origin main',
      '',
      '# Push',
      'git push origin feature/auth',
      'git push -u origin feature/auth  # Set upstream',
      '',
      '# Rebase onto main',
      'git rebase main',
      'git rebase -i HEAD~3        # Interactive rebase last 3 commits',
      '',
      '# Cherry-pick',
      'git cherry-pick abc123',
      '```',
      '',
      '### Useful Tricks',
      '',
      '```bash',
      '# Clean untracked files (dry run first)',
      'git clean -n',
      'git clean -fd',
      '',
      '# Find large files in history',
      'git rev-list --objects --all | git cat-file --batch-check | sort -k3nr | head',
      '',
      '# Bisect to find bug',
      'git bisect start',
      'git bisect bad              # Current commit is bad',
      'git bisect good v1.0        # Known good commit',
      '```',
    ].join('\n'),
  },
  {
    title: 'TypeScript Utility Types',
    type: 'cheatsheet',
    collection: 'frontend',
    summary: 'Reference guide for built-in TypeScript utility types with practical examples.',
    tags: ['typescript', 'types', 'frontend', 'cheatsheet'],
    mdx: [
      '## Partial and Required',
      '',
      '`Partial<T>` makes all properties optional. `Required<T>` makes them all required. These are inverses of each other and are the most commonly used utility types.',
      '',
      '```typescript',
      'interface User {',
      '  id: string;',
      '  name: string;',
      '  email: string;',
      '  avatar?: string;',
      '}',
      '',
      '// All fields optional — useful for update payloads',
      'type UpdateUser = Partial<User>;',
      '// { id?: string; name?: string; email?: string; avatar?: string }',
      '',
      '// All fields required — useful for complete objects',
      'type CompleteUser = Required<User>;',
      '// { id: string; name: string; email: string; avatar: string }',
      '```',
      '',
      '## Pick and Omit',
      '',
      'Select or exclude specific properties from a type. Use these to create focused types from larger interfaces.',
      '',
      '```typescript',
      '// Only keep specific fields',
      "type UserPreview = Pick<User, 'id' | 'name'>;",
      '// { id: string; name: string }',
      '',
      '// Remove specific fields',
      "type CreateUser = Omit<User, 'id'>;",
      '// { name: string; email: string; avatar?: string }',
      '',
      '// Combine for complex transformations',
      "type UserForm = Partial<Omit<User, 'id'>> & { id: string };",
      '```',
      '',
      '## Record',
      '',
      'Create an object type with specific key and value types. Extremely useful for lookup maps and dictionaries.',
      '',
      '```typescript',
      "type Role = 'admin' | 'editor' | 'viewer';",
      '',
      'const permissions: Record<Role, string[]> = {',
      "  admin: ['read', 'write', 'delete', 'manage'],",
      "  editor: ['read', 'write'],",
      "  viewer: ['read'],",
      '};',
      '',
      '// Dynamic keys',
      'type PageCache = Record<string, { html: string; cachedAt: Date }>;',
      '```',
      '',
      '## Extract and Exclude',
      '',
      'Filter union types. `Extract` keeps matching members, `Exclude` removes them.',
      '',
      '```typescript',
      "type Event = 'click' | 'scroll' | 'mousemove' | 'keydown' | 'keyup';",
      '',
      "type MouseEvent = Extract<Event, 'click' | 'scroll' | 'mousemove'>;",
      "// 'click' | 'scroll' | 'mousemove'",
      '',
      "type KeyboardEvent = Exclude<Event, 'click' | 'scroll' | 'mousemove'>;",
      "// 'keydown' | 'keyup'",
      '```',
      '',
      '## ReturnType and Parameters',
      '',
      'Extract types from function signatures. Invaluable when working with third-party libraries.',
      '',
      '```typescript',
      'function createUser(name: string, email: string, role: Role) {',
      '  return { id: crypto.randomUUID(), name, email, role, createdAt: new Date() };',
      '}',
      '',
      'type NewUser = ReturnType<typeof createUser>;',
      '// { id: string; name: string; email: string; role: Role; createdAt: Date }',
      '',
      'type CreateUserArgs = Parameters<typeof createUser>;',
      '// [name: string, email: string, role: Role]',
      '```',
      '',
      '### Conditional and Mapped Types',
      '',
      '```typescript',
      '// NonNullable removes null and undefined',
      'type MaybeString = string | null | undefined;',
      'type DefiniteString = NonNullable<MaybeString>; // string',
      '',
      '// Readonly makes all properties readonly',
      'type FrozenUser = Readonly<User>;',
      '',
      '// Custom mapped type',
      'type Nullable<T> = { [K in keyof T]: T[K] | null };',
      'type NullableUser = Nullable<User>;',
      '```',
    ].join('\n'),
  },
  {
    title: 'PostgreSQL Performance Tips',
    type: 'tip',
    collection: 'database',
    summary: 'Practical tips for optimizing PostgreSQL query performance.',
    tags: ['postgresql', 'performance', 'database', 'optimization'],
    mdx: [
      '## Use EXPLAIN ANALYZE',
      '',
      'Always start with `EXPLAIN ANALYZE` to understand what the query planner is doing. The `ANALYZE` keyword actually runs the query, giving you real execution times instead of estimates.',
      '',
      '```sql',
      'EXPLAIN ANALYZE',
      'SELECT p.title, c.name as collection',
      'FROM pages p',
      'JOIN collections c ON c.id = p.collection_id',
      "WHERE p.status = 'published'",
      'ORDER BY p.created_at DESC',
      'LIMIT 20;',
      '```',
      '',
      'Look for sequential scans on large tables, nested loops with high row counts, and large differences between estimated and actual rows. These are your optimization targets.',
      '',
      '## Index Strategy',
      '',
      'Create indexes based on your actual query patterns, not just on every column. Composite indexes should match your WHERE clause column order.',
      '',
      '```sql',
      '-- Composite index for common query pattern',
      'CREATE INDEX idx_pages_status_created',
      'ON pages (status, created_at DESC);',
      '',
      '-- Partial index for published pages only',
      'CREATE INDEX idx_pages_published',
      'ON pages (created_at DESC)',
      "WHERE status = 'published';",
      '',
      '-- GIN index for full-text search',
      'CREATE INDEX idx_chunks_fts ON chunks USING GIN (fts);',
      '',
      '-- Check index usage',
      'SELECT indexrelname, idx_scan, idx_tup_read',
      'FROM pg_stat_user_indexes',
      'ORDER BY idx_scan DESC;',
      '```',
      '',
      'Partial indexes are powerful — they\'re smaller and faster because they only index rows matching the WHERE condition.',
      '',
      '## Connection Pooling',
      '',
      'Each PostgreSQL connection consumes about 10MB of memory. Use connection pooling to share connections across requests.',
      '',
      '```typescript',
      "import { Pool } from 'pg';",
      '',
      'const pool = new Pool({',
      '  connectionString: process.env.DATABASE_URL,',
      '  max: 20,              // Maximum connections',
      '  idleTimeoutMillis: 30000,',
      '  connectionTimeoutMillis: 2000,',
      '});',
      '',
      '// Always release connections back to the pool',
      'const client = await pool.connect();',
      'try {',
      "  const result = await client.query('SELECT ...');",
      '  return result.rows;',
      '} finally {',
      '  client.release();',
      '}',
      '```',
      '',
      '## Batch Operations',
      '',
      'Avoid N+1 queries. Use `ANY` with arrays instead of multiple individual queries:',
      '',
      '```sql',
      '-- Bad: N queries',
      'SELECT * FROM pages WHERE id = $1;  -- repeated N times',
      '',
      '-- Good: 1 query',
      'SELECT * FROM pages WHERE id = ANY($1::uuid[]);',
      '```',
      '',
      '### Vacuum and Statistics',
      '',
      'PostgreSQL needs up-to-date statistics for good query plans. Autovacuum handles this, but after bulk operations you should run it manually:',
      '',
      '```sql',
      '-- Update statistics after bulk insert',
      'ANALYZE pages;',
      '',
      '-- Check autovacuum status',
      'SELECT relname, last_vacuum, last_autovacuum, last_analyze',
      'FROM pg_stat_user_tables',
      'ORDER BY last_autovacuum DESC NULLS LAST;',
      '```',
    ].join('\n'),
  },
  {
    title: 'React useEffect Cleanup Patterns',
    type: 'tip',
    collection: 'frontend',
    summary: 'Proper cleanup patterns to prevent memory leaks and stale state in React effects.',
    tags: ['react', 'hooks', 'useeffect', 'frontend', 'cleanup'],
    mdx: [
      '## Why Cleanup Matters',
      '',
      'Every `useEffect` that creates a subscription, timer, or async operation needs cleanup. Without it, you get memory leaks, stale state updates, and the dreaded "Can\'t perform a React state update on an unmounted component" warning.',
      '',
      'The cleanup function runs before the effect re-runs and when the component unmounts. Think of it as the "undo" for whatever your effect sets up.',
      '',
      '## AbortController for Fetch Requests',
      '',
      'The most common pattern — cancel in-flight requests when the component unmounts or dependencies change:',
      '',
      '```typescript',
      'useEffect(() => {',
      '  const controller = new AbortController();',
      '',
      '  async function fetchData() {',
      '    try {',
      '      const res = await fetch(`/api/posts/' + D + '{id}`, {',
      '        signal: controller.signal,',
      '      });',
      '      const data = await res.json();',
      '      setPosts(data);',
      '    } catch (err) {',
      "      if (err instanceof DOMException && err.name === 'AbortError') {",
      '        return; // Expected — request was cancelled',
      '      }',
      '      setError(err);',
      '    }',
      '  }',
      '',
      '  fetchData();',
      '  return () => controller.abort();',
      '}, [id]);',
      '```',
      '',
      '## Event Listeners',
      '',
      'Always remove event listeners in cleanup. Use the same function reference for both add and remove:',
      '',
      '```typescript',
      'useEffect(() => {',
      '  function handleResize() {',
      '    setWidth(window.innerWidth);',
      '  }',
      '',
      "  window.addEventListener('resize', handleResize);",
      "  return () => window.removeEventListener('resize', handleResize);",
      '}, []);',
      '```',
      '',
      '## Timers and Intervals',
      '',
      'Clear timeouts and intervals to prevent callbacks firing after unmount:',
      '',
      '```typescript',
      'useEffect(() => {',
      '  const intervalId = setInterval(() => {',
      '    setCount(c => c + 1);',
      '  }, 1000);',
      '',
      '  return () => clearInterval(intervalId);',
      '}, []);',
      '```',
      '',
      '## WebSocket Connections',
      '',
      'Close WebSocket connections cleanly:',
      '',
      '```typescript',
      'useEffect(() => {',
      "  const ws = new WebSocket('wss://api.example.com/feed');",
      '',
      '  ws.onmessage = (event) => {',
      '    const data = JSON.parse(event.data);',
      '    setMessages(prev => [...prev, data]);',
      '  };',
      '',
      '  ws.onerror = (error) => {',
      "    console.error('WebSocket error:', error);",
      '  };',
      '',
      '  return () => {',
      '    if (ws.readyState === WebSocket.OPEN) {',
      "      ws.close(1000, 'Component unmounting');",
      '    }',
      '  };',
      '}, []);',
      '```',
      '',
      '### Boolean Flag Pattern',
      '',
      "For effects where you can't cancel the operation, use a flag to prevent stale updates:",
      '',
      '```typescript',
      'useEffect(() => {',
      '  let cancelled = false;',
      '',
      '  async function loadData() {',
      '    const result = await expensiveComputation(input);',
      '    if (!cancelled) {',
      '      setResult(result);',
      '    }',
      '  }',
      '',
      '  loadData();',
      '  return () => { cancelled = true; };',
      '}, [input]);',
      '```',
      '',
      'This is a last resort — prefer AbortController when the underlying API supports it.',
    ].join('\n'),
  },
  {
    title: 'JWT Authentication from Scratch',
    type: 'tutorial',
    collection: 'security',
    summary: 'Implement JWT-based authentication with access and refresh tokens.',
    tags: ['jwt', 'authentication', 'security', 'tokens', 'auth'],
    mdx: [
      '## How JWT Authentication Works',
      '',
      "JSON Web Tokens encode claims as a signed JSON payload. The server creates a token after verifying credentials, and the client sends it with subsequent requests. The server validates the signature without hitting a database — this is what makes JWTs stateless.",
      '',
      "A JWT has three parts separated by dots: header (algorithm), payload (claims), and signature. The signature ensures the token hasn't been tampered with.",
      '',
      '## Token Generation',
      '',
      '```typescript',
      "import { SignJWT, jwtVerify } from 'jose';",
      '',
      'const ACCESS_SECRET = new TextEncoder().encode(process.env.JWT_SECRET!);',
      'const REFRESH_SECRET = new TextEncoder().encode(process.env.REFRESH_SECRET!);',
      '',
      'async function generateTokens(userId: string, role: string) {',
      '  const accessToken = await new SignJWT({ sub: userId, role })',
      "    .setProtectedHeader({ alg: 'HS256' })",
      '    .setIssuedAt()',
      "    .setExpirationTime('15m')",
      '    .sign(ACCESS_SECRET);',
      '',
      '  const refreshToken = await new SignJWT({ sub: userId })',
      "    .setProtectedHeader({ alg: 'HS256' })",
      '    .setIssuedAt()',
      "    .setExpirationTime('7d')",
      '    .sign(REFRESH_SECRET);',
      '',
      '  return { accessToken, refreshToken };',
      '}',
      '```',
      '',
      'Short-lived access tokens (15 minutes) limit the damage window if a token is compromised. Refresh tokens (7 days) let users stay logged in without re-entering credentials.',
      '',
      '## Login Endpoint',
      '',
      '```typescript',
      'export async function POST(request: NextRequest) {',
      '  const { email, password } = await request.json();',
      '',
      '  const user = await db.query.users.findFirst({',
      '    where: (users, { eq }) => eq(users.email, email),',
      '  });',
      '',
      '  if (!user || !(await bcrypt.compare(password, user.passwordHash))) {',
      '    return NextResponse.json(',
      "      { error: 'Invalid credentials' },",
      '      { status: 401 }',
      '    );',
      '  }',
      '',
      '  const tokens = await generateTokens(user.id, user.role);',
      '',
      '  const response = NextResponse.json({ accessToken: tokens.accessToken });',
      "  response.cookies.set('refreshToken', tokens.refreshToken, {",
      '    httpOnly: true,',
      "    secure: process.env.NODE_ENV === 'production',",
      "    sameSite: 'lax',",
      '    maxAge: 7 * 24 * 60 * 60, // 7 days',
      "    path: '/api/auth/refresh',",
      '  });',
      '',
      '  return response;',
      '}',
      '```',
      '',
      '## Token Verification Middleware',
      '',
      '```typescript',
      'async function verifyAuth(request: NextRequest) {',
      "  const authHeader = request.headers.get('authorization');",
      "  if (!authHeader?.startsWith('Bearer ')) {",
      "    throw new Error('Missing token');",
      '  }',
      '',
      '  const token = authHeader.slice(7);',
      '  try {',
      '    const { payload } = await jwtVerify(token, ACCESS_SECRET);',
      '    return { userId: payload.sub as string, role: payload.role as string };',
      '  } catch {',
      "    throw new Error('Invalid or expired token');",
      '  }',
      '}',
      '```',
      '',
      '## Refresh Token Rotation',
      '',
      '```typescript',
      'export async function POST(request: NextRequest) {',
      "  const refreshToken = request.cookies.get('refreshToken')?.value;",
      '  if (!refreshToken) {',
      "    return NextResponse.json({ error: 'No refresh token' }, { status: 401 });",
      '  }',
      '',
      '  try {',
      '    const { payload } = await jwtVerify(refreshToken, REFRESH_SECRET);',
      "    const tokens = await generateTokens(payload.sub as string, 'user');",
      '',
      '    const response = NextResponse.json({',
      '      accessToken: tokens.accessToken,',
      '    });',
      "    response.cookies.set('refreshToken', tokens.refreshToken, {",
      '      httpOnly: true,',
      '      secure: true,',
      "      sameSite: 'lax',",
      '      maxAge: 7 * 24 * 60 * 60,',
      "      path: '/api/auth/refresh',",
      '    });',
      '',
      '    return response;',
      '  } catch {',
      "    return NextResponse.json({ error: 'Invalid refresh token' }, { status: 401 });",
      '  }',
      '}',
      '```',
      '',
      '### Security Considerations',
      '',
      'Store access tokens in memory (not localStorage). Store refresh tokens in httpOnly cookies. Always use HTTPS in production. Implement token revocation for logout by maintaining a blocklist of revoked token IDs in Redis or your database.',
    ].join('\n'),
  },
  {
    title: 'SQL Injection Prevention',
    type: 'note',
    collection: 'security',
    summary: 'Understanding and preventing SQL injection attacks in modern applications.',
    tags: ['sql-injection', 'security', 'database', 'owasp'],
    mdx: [
      '## What Is SQL Injection?',
      '',
      "SQL injection occurs when user input is concatenated directly into SQL queries. An attacker can manipulate the query structure to read unauthorized data, modify records, or even drop tables. It remains in the OWASP Top 10 because developers still make this mistake.",
      '',
      '```typescript',
      '// VULNERABLE — never do this',
      "const query = `SELECT * FROM users WHERE email = '" + D + "{email}'`;",
      '',
      "// If email is: ' OR '1'='1' --",
      "// Query becomes: SELECT * FROM users WHERE email = '' OR '1'='1' --'",
      '// This returns ALL users',
      '```',
      '',
      '## Parameterized Queries',
      '',
      'The primary defense is parameterized queries (prepared statements). The database treats parameters as data, never as SQL code:',
      '',
      '```typescript',
      '// Safe — parameterized query with pg',
      'const result = await pool.query(',
      "  'SELECT * FROM users WHERE email = $1',",
      '  [email]',
      ');',
      '',
      '// Safe — parameterized query with Drizzle ORM',
      'const user = await db.query.users.findFirst({',
      '  where: (users, { eq }) => eq(users.email, email),',
      '});',
      '```',
      '',
      '## ORM Protection',
      '',
      'ORMs like Drizzle automatically parameterize queries. But be careful with raw SQL escape hatches:',
      '',
      '```typescript',
      "import { sql } from 'drizzle-orm';",
      '',
      '// Safe — sql template tag parameterizes automatically',
      'const results = await db.execute(',
      "  sql`SELECT * FROM pages WHERE title ILIKE " + D + "{'%' + search + '%'}`",
      ');',
      '',
      '// DANGEROUS — string interpolation in raw queries',
      'const results = await db.execute(',
      "  sql.raw(`SELECT * FROM pages WHERE title ILIKE '%" + D + "{search}%'`)",
      ');',
      '```',
      '',
      '## Input Validation',
      '',
      'Validation is a defense-in-depth layer, not a replacement for parameterized queries:',
      '',
      '```typescript',
      "import { z } from 'zod';",
      '',
      'const SearchSchema = z.object({',
      '  query: z.string().min(1).max(200),',
      '  page: z.coerce.number().int().positive().default(1),',
      '  limit: z.coerce.number().int().min(1).max(100).default(20),',
      '});',
      '',
      '// Validate before any database operation',
      'const params = SearchSchema.parse(request.query);',
      '```',
      '',
      '### Stored Procedures and Least Privilege',
      '',
      "Limit database user permissions. Your application's database user should only have the permissions it needs:",
      '',
      '```sql',
      '-- Create a restricted user for the application',
      "CREATE ROLE app_user WITH LOGIN PASSWORD 'secure_password';",
      'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;',
      'REVOKE DROP, CREATE ON SCHEMA public FROM app_user;',
      '',
      '-- Never let the app user run DDL',
      'REVOKE ALL ON DATABASE myapp FROM app_user;',
      'GRANT CONNECT ON DATABASE myapp TO app_user;',
      '```',
      '',
      "Defense in depth means that even if an injection vulnerability exists, the attacker's capabilities are limited by the database user's permissions.",
    ].join('\n'),
  },
  {
    title: 'Vector Embeddings for Search',
    type: 'tutorial',
    collection: 'ai-ml',
    summary: 'Implement semantic search using vector embeddings and pgvector.',
    tags: ['embeddings', 'vector-search', 'pgvector', 'ai', 'semantic-search'],
    mdx: [
      '## What Are Vector Embeddings?',
      '',
      'Vector embeddings are numerical representations of text (or images, audio, etc.) in a high-dimensional space. Similar content produces vectors that are close together, enabling semantic search — finding results by meaning rather than exact keyword matches.',
      '',
      "For example, a search for \"container orchestration\" would match documents about Kubernetes and Docker Swarm, even if those exact words don't appear in the query.",
      '',
      '## Generating Embeddings',
      '',
      "Use OpenAI's embedding API or any compatible provider:",
      '',
      '```typescript',
      "import OpenAI from 'openai';",
      '',
      'const openai = new OpenAI();',
      '',
      'async function generateEmbedding(text: string): Promise<number[]> {',
      '  const response = await openai.embeddings.create({',
      "    model: 'text-embedding-3-small',",
      '    input: text,',
      '    dimensions: 1536,',
      '  });',
      '  return response.data[0].embedding;',
      '}',
      '```',
      '',
      'The `text-embedding-3-small` model produces 1536-dimensional vectors. Smaller dimensions are faster but less accurate. For most use cases, 1536 is a good balance.',
      '',
      '## Storing Embeddings with pgvector',
      '',
      'pgvector extends PostgreSQL with vector operations. Store embeddings alongside your content:',
      '',
      '```sql',
      '-- Enable the extension',
      'CREATE EXTENSION IF NOT EXISTS vector;',
      '',
      '-- Create embeddings table',
      'CREATE TABLE chunk_embeddings (',
      '  chunk_id UUID REFERENCES chunks(id) ON DELETE CASCADE,',
      '  embedding_model TEXT NOT NULL,',
      '  embedding vector(1536)',
      ');',
      '',
      '-- Create an IVFFlat index for fast similarity search',
      'CREATE INDEX ON chunk_embeddings',
      'USING ivfflat (embedding vector_cosine_ops)',
      'WITH (lists = 100);',
      '```',
      '',
      '## Semantic Search Query',
      '',
      'Find the most similar chunks using cosine distance:',
      '',
      '```typescript',
      'async function semanticSearch(query: string, limit = 10) {',
      '  const queryEmbedding = await generateEmbedding(query);',
      '',
      '  const results = await pool.query(`',
      '    SELECT',
      '      c.content,',
      '      c.heading_path,',
      '      p.title,',
      '      p.slug,',
      '      1 - (ce.embedding <=> $1::vector) as similarity',
      '    FROM chunk_embeddings ce',
      '    JOIN chunks c ON c.id = ce.chunk_id',
      '    JOIN pages p ON p.id = c.page_id',
      "    WHERE p.status = 'published'",
      '    ORDER BY ce.embedding <=> $1::vector',
      '    LIMIT $2',
      '  `, [JSON.stringify(queryEmbedding), limit]);',
      '',
      '  return results.rows;',
      '}',
      '```',
      '',
      'The `<=>` operator computes cosine distance. Lower distance means higher similarity. We subtract from 1 to get a similarity score where 1.0 is identical.',
      '',
      '## Hybrid Search',
      '',
      'Combine vector search with full-text search for best results:',
      '',
      '```typescript',
      'async function hybridSearch(query: string, limit = 10) {',
      '  const queryEmbedding = await generateEmbedding(query);',
      '',
      '  const results = await pool.query(`',
      '    WITH semantic AS (',
      '      SELECT ce.chunk_id, 1 - (ce.embedding <=> $1::vector) as score',
      '      FROM chunk_embeddings ce',
      '      ORDER BY ce.embedding <=> $1::vector',
      '      LIMIT 50',
      '    ),',
      '    fulltext AS (',
      '      SELECT c.id as chunk_id,',
      "             ts_rank(c.fts, websearch_to_tsquery('english', $2)) as score",
      '      FROM chunks c',
      "      WHERE c.fts @@ websearch_to_tsquery('english', $2)",
      '      LIMIT 50',
      '    )',
      '    SELECT DISTINCT c.content, p.title, p.slug,',
      '      COALESCE(s.score, 0) * 0.7 + COALESCE(f.score, 0) * 0.3 as combined_score',
      '    FROM chunks c',
      '    JOIN pages p ON p.id = c.page_id',
      '    LEFT JOIN semantic s ON s.chunk_id = c.id',
      '    LEFT JOIN fulltext f ON f.chunk_id = c.id',
      '    WHERE s.chunk_id IS NOT NULL OR f.chunk_id IS NOT NULL',
      '    ORDER BY combined_score DESC',
      '    LIMIT $3',
      '  `, [JSON.stringify(queryEmbedding), query, limit]);',
      '',
      '  return results.rows;',
      '}',
      '```',
      '',
      '### Indexing Strategy',
      '',
      'For tables under 1M rows, IVFFlat indexes work well. For larger datasets, consider HNSW indexes which provide better recall at the cost of more memory:',
      '',
      '```sql',
      'CREATE INDEX ON chunk_embeddings',
      'USING hnsw (embedding vector_cosine_ops)',
      'WITH (m = 16, ef_construction = 64);',
      '```',
    ].join('\n'),
  },
  {
    title: 'Linux Command Line Cheatsheet',
    type: 'cheatsheet',
    collection: 'devops',
    summary: 'Essential Linux commands for developers and system administrators.',
    tags: ['linux', 'bash', 'cli', 'devops', 'sysadmin'],
    mdx: [
      '## File Operations',
      '',
      '```bash',
      '# List files with details',
      'ls -lah                     # All files, human-readable sizes',
      'ls -lt                      # Sort by modification time',
      '',
      '# Find files',
      'find . -name "*.ts" -type f',
      'find . -mtime -7 -name "*.log"  # Modified in last 7 days',
      'find . -size +100M              # Files larger than 100MB',
      '',
      '# File content',
      'cat file.txt                # Print entire file',
      'head -20 file.txt           # First 20 lines',
      'tail -f /var/log/app.log    # Follow log in real-time',
      'less +F /var/log/app.log    # Less with follow mode',
      '```',
      '',
      '## Text Processing',
      '',
      '```bash',
      '# Search with grep',
      'grep -r "TODO" src/          # Recursive search',
      'grep -rn "import.*from" src/ # With line numbers',
      'grep -c "error" app.log      # Count matches',
      'grep -v "debug" app.log      # Invert match (exclude)',
      '',
      '# Transform with sed',
      "sed 's/old/new/g' file.txt           # Replace all occurrences",
      "sed -i 's/localhost/0.0.0.0/g' .env  # In-place edit",
      '',
      '# Column extraction with awk',
      "awk '{print $1, $3}' access.log      # Print columns 1 and 3",
      "awk -F: '{print $1}' /etc/passwd     # Custom delimiter",
      '```',
      '',
      '## Process Management',
      '',
      '```bash',
      '# View processes',
      'ps aux | grep node',
      'top -o %MEM                  # Sort by memory usage',
      'htop                         # Interactive process viewer',
      '',
      '# Kill processes',
      'kill -15 <pid>               # Graceful shutdown (SIGTERM)',
      'kill -9 <pid>                # Force kill (SIGKILL)',
      'pkill -f "node server.js"   # Kill by command pattern',
      '',
      '# Background jobs',
      'command &                    # Run in background',
      'nohup command &              # Survive terminal close',
      'jobs                         # List background jobs',
      'fg %1                        # Bring job 1 to foreground',
      '```',
      '',
      '## Disk and Memory',
      '',
      '```bash',
      '# Disk usage',
      'df -h                        # Filesystem usage',
      'du -sh */                    # Directory sizes',
      'du -sh * | sort -rh | head   # Largest items first',
      'ncdu /var                    # Interactive disk usage',
      '',
      '# Memory',
      'free -h                      # Memory usage',
      'vmstat 1 5                   # Virtual memory stats (5 samples)',
      '```',
      '',
      '## Networking',
      '',
      '```bash',
      '# Check connectivity',
      'curl -I https://example.com  # HTTP headers only',
      'curl -s url | jq .           # Fetch and format JSON',
      'wget -q -O- url              # Quiet download to stdout',
      '',
      '# Ports and connections',
      'ss -tlnp                     # Listening TCP ports',
      'lsof -i :3000               # What\'s using port 3000',
      'netstat -tulpn               # All listening ports',
      '',
      '# DNS',
      'dig example.com              # DNS lookup',
      'nslookup example.com         # Simple DNS query',
      'host example.com             # Reverse lookup',
      '```',
      '',
      '### Compression and Archives',
      '',
      '```bash',
      '# tar',
      'tar czf archive.tar.gz dir/  # Create gzipped archive',
      'tar xzf archive.tar.gz       # Extract gzipped archive',
      'tar tf archive.tar.gz        # List contents',
      '',
      '# zip',
      'zip -r archive.zip dir/      # Create zip',
      'unzip archive.zip             # Extract zip',
      'unzip -l archive.zip          # List contents',
      '```',
    ].join('\n'),
  },
  {
    title: 'Next.js Caching Strategies',
    type: 'tip',
    collection: 'backend',
    summary: 'Understanding and configuring caching in Next.js App Router.',
    tags: ['nextjs', 'caching', 'performance', 'backend'],
    mdx: [
      '## The Four Caching Layers',
      '',
      'Next.js App Router has four distinct caching mechanisms. Understanding when each applies is critical for both performance and correctness.',
      '',
      '**Request Memoization** deduplicates identical fetch calls within a single server render. If multiple components fetch the same URL, only one network request is made. This happens automatically for `fetch()` calls with the same URL and options.',
      '',
      '**Data Cache** persists fetch responses across requests and deployments. This is the most impactful cache and the one most likely to cause stale data bugs.',
      '',
      '**Full Route Cache** stores the rendered HTML and RSC payload for static routes at build time.',
      '',
      '**Router Cache** stores RSC payloads on the client for visited routes, enabling instant back/forward navigation.',
      '',
      '## Controlling the Data Cache',
      '',
      '```typescript',
      '// Cached indefinitely (default in production)',
      "const data = await fetch('https://api.example.com/posts');",
      '',
      '// Revalidate every 60 seconds',
      "const data = await fetch('https://api.example.com/posts', {",
      '  next: { revalidate: 60 },',
      '});',
      '',
      '// Never cache — always fresh',
      "const data = await fetch('https://api.example.com/posts', {",
      "  cache: 'no-store',",
      '});',
      '```',
      '',
      '## Route Segment Configuration',
      '',
      'Control caching at the route level:',
      '',
      '```typescript',
      '// app/dashboard/page.tsx',
      '',
      '// Force dynamic rendering — no caching',
      "export const dynamic = 'force-dynamic';",
      '',
      '// Or set revalidation period',
      'export const revalidate = 300; // 5 minutes',
      '',
      '// Force static generation',
      "export const dynamic = 'force-static';",
      '```',
      '',
      '## On-Demand Revalidation',
      '',
      'Invalidate cached data when content changes:',
      '',
      '```typescript',
      "import { revalidatePath, revalidateTag } from 'next/cache';",
      '',
      '// Revalidate a specific path',
      'export async function updatePost(id: string, data: PostData) {',
      '  await db.update(posts).set(data).where(eq(posts.id, id));',
      "  revalidatePath('/blog');",
      "  revalidatePath(`/blog/" + D + "{id}`);",
      '}',
      '',
      '// Tag-based revalidation',
      "const posts = await fetch('https://api.example.com/posts', {",
      "  next: { tags: ['posts'] },",
      '});',
      '',
      "// Later, invalidate all fetches tagged 'posts'",
      "revalidateTag('posts');",
      '```',
      '',
      '## unstable_cache for Database Queries',
      '',
      'For non-fetch data sources (like direct database queries), use `unstable_cache`:',
      '',
      '```typescript',
      "import { unstable_cache } from 'next/cache';",
      '',
      'const getCachedPosts = unstable_cache(',
      '  async (collectionId: string) => {',
      '    return db.query.posts.findMany({',
      '      where: (posts, { eq }) => eq(posts.collectionId, collectionId),',
      '      orderBy: (posts, { desc }) => [desc(posts.publishedAt)],',
      '    });',
      '  },',
      "  ['posts-by-collection'],",
      "  { revalidate: 300, tags: ['posts'] }",
      ');',
      '```',
      '',
      '### Common Pitfalls',
      '',
      'Using `cookies()` or `headers()` in a Server Component automatically opts the entire route into dynamic rendering. If you only need auth info, consider passing it as a prop from a layout that handles authentication, keeping leaf components cacheable.',
    ].join('\n'),
  },
  {
    title: 'Building a RAG Pipeline',
    type: 'tutorial',
    collection: 'ai-ml',
    summary: 'Build a Retrieval-Augmented Generation pipeline for knowledge-base Q&A.',
    tags: ['rag', 'llm', 'ai', 'embeddings', 'retrieval'],
    mdx: [
      '## What Is RAG?',
      '',
      "Retrieval-Augmented Generation combines a retrieval system with a language model. Instead of relying solely on the LLM's training data, RAG fetches relevant documents from your knowledge base and includes them in the prompt. This grounds the model's responses in your actual content, reducing hallucinations.",
      '',
      'The pipeline has three stages: indexing (prepare and store documents), retrieval (find relevant chunks), and generation (synthesize an answer).',
      '',
      '## Document Indexing Pipeline',
      '',
      'Split documents into chunks, generate embeddings, and store them:',
      '',
      '```typescript',
      'async function indexDocument(pageId: string, content: string) {',
      '  // Split by headings for semantic coherence',
      '  const chunks = splitByHeadings(content);',
      '',
      '  for (const chunk of chunks) {',
      '    // Store the chunk',
      '    const [inserted] = await db.insert(chunksTable).values({',
      '      pageId,',
      '      content: chunk.text,',
      "      contentType: 'markdown',",
      '      headingPath: chunk.headings,',
      "      anchorId: slugify(chunk.headings.at(-1) || ''),",
      "      fts: sql`to_tsvector('english', " + D + "{chunk.text})`,",
      '    }).returning();',
      '',
      '    // Generate and store embedding',
      '    const embedding = await generateEmbedding(chunk.text);',
      '    await db.insert(chunkEmbeddingsTable).values({',
      '      chunkId: inserted.id,',
      "      embeddingModel: 'text-embedding-3-small',",
      '      embedding: sql`' + D + '{JSON.stringify(embedding)}::vector`,',
      '    });',
      '  }',
      '}',
      '```',
      '',
      '## Retrieval with Context Window',
      '',
      'Retrieve relevant chunks and build a context window for the LLM:',
      '',
      '```typescript',
      'async function retrieveContext(query: string, maxTokens = 4000) {',
      '  const queryEmbedding = await generateEmbedding(query);',
      '',
      '  const results = await pool.query(`',
      '    SELECT c.content, c.heading_path, p.title, p.slug,',
      '           1 - (ce.embedding <=> $1::vector) as similarity',
      '    FROM chunk_embeddings ce',
      '    JOIN chunks c ON c.id = ce.chunk_id',
      '    JOIN pages p ON p.id = c.page_id',
      "    WHERE p.status = 'published'",
      '    ORDER BY ce.embedding <=> $1::vector',
      '    LIMIT 10',
      '  `, [JSON.stringify(queryEmbedding)]);',
      '',
      '  // Build context string within token budget',
      "  let context = '';",
      '  for (const row of results.rows) {',
      '    const section = `## ' + D + '{row.title}\\n' + D + '{row.content}\\n\\n`;',
      '    if (estimateTokens(context + section) > maxTokens) break;',
      '    context += section;',
      '  }',
      '',
      '  return { context, sources: results.rows };',
      '}',
      '```',
      '',
      '## Generation with Citations',
      '',
      'Send the retrieved context to the LLM with instructions to cite sources:',
      '',
      '```typescript',
      'async function generateAnswer(query: string) {',
      '  const { context, sources } = await retrieveContext(query);',
      '',
      '  const response = await openai.chat.completions.create({',
      "    model: 'gpt-4o',",
      '    messages: [',
      '      {',
      "        role: 'system',",
      '        content: `You are a helpful technical assistant. Answer questions',
      "based ONLY on the provided context. If the context doesn't contain",
      'enough information, say so. Cite sources using [Title](slug) format.`',
      '      },',
      '      {',
      "        role: 'user',",
      '        content: `Context:\\n' + D + '{context}\\n\\nQuestion: ' + D + '{query}`',
      '      }',
      '    ],',
      '    temperature: 0.3,',
      '  });',
      '',
      '  return {',
      '    answer: response.choices[0].message.content,',
      '    sources: sources.map(s => ({ title: s.title, slug: s.slug })),',
      '  };',
      '}',
      '```',
      '',
      '## Chunking Strategies',
      '',
      'How you split documents significantly impacts retrieval quality:',
      '',
      '```typescript',
      'function splitByHeadings(markdown: string) {',
      '  const sections: { headings: string[]; text: string }[] = [];',
      "  const lines = markdown.split('\\n');",
      '  let headings: string[] = [];',
      '  let buffer: string[] = [];',
      '',
      '  for (const line of lines) {',
      "    const match = line.match(/^(#{1,3})\\s+(.+)/);",
      '    if (match) {',
      '      if (buffer.length) {',
      "        sections.push({ headings: [...headings], text: buffer.join('\\n') });",
      '        buffer = [];',
      '      }',
      '      const level = match[1].length;',
      '      headings = headings.slice(0, level - 1);',
      '      headings.push(match[2]);',
      '    }',
      '    buffer.push(line);',
      '  }',
      '',
      '  if (buffer.length) {',
      "    sections.push({ headings: [...headings], text: buffer.join('\\n') });",
      '  }',
      '',
      '  return sections;',
      '}',
      '```',
      '',
      '### Evaluation and Improvement',
      '',
      'Measure RAG quality with three metrics: retrieval precision (are the fetched chunks relevant?), answer faithfulness (does the answer stick to the context?), and answer relevance (does it actually answer the question?). Log queries and retrieved chunks to build an evaluation dataset over time.',
    ].join('\n'),
  },
];

// ── Main Seed Function ───────────────────────────────────────────────────────

async function seed() {
  const client = await pool.connect();

  try {
    await client.query('BEGIN');

    console.log('🗑️  Clearing existing data...');
    const deleteOrder = [
      'messages', 'conversations', 'chunk_embeddings', 'chunks',
      'page_revisions', 'page_tags', 'page_relations', 'assets',
      'pages', 'collections', 'ai_usage_logs', 'ai_models',
      'ai_providers', 'users',
    ];
    for (const table of deleteOrder) {
      await client.query(`DELETE FROM ${table}`);
    }

    // ── Users ──────────────────────────────────────────────────────────────
    console.log('👤 Creating admin user...');
    const adminEmail = process.env.SEED_ADMIN_EMAIL;
    const adminPassword = process.env.SEED_ADMIN_PASSWORD;
    const adminName = process.env.SEED_ADMIN_NAME || 'Admin';
    if (!adminEmail || !adminPassword) {
      throw new Error(
        'SEED_ADMIN_EMAIL and SEED_ADMIN_PASSWORD must be set in .env.local'
      );
    }
    const passwordHash = await hash(adminPassword, 12);
    const userResult = await client.query(
      `INSERT INTO users (email, password_hash, name, role)
       VALUES ($1, $2, $3, $4) RETURNING id`,
      [adminEmail, passwordHash, adminName, 'admin']
    );
    const userId = userResult.rows[0].id;
    console.log(`   User ID: ${userId}`);

    // Optional: create E2E smoke test user
    const e2eEmail = process.env.E2E_EMAIL;
    const e2ePassword = process.env.E2E_PASSWORD;
    if (e2eEmail && e2ePassword) {
      console.log('🧪 Creating E2E test user...');
      const e2eHash = await hash(e2ePassword, 12);
      await client.query(
        `INSERT INTO users (email, password_hash, name, role)
         VALUES ($1, $2, $3, $4)`,
        [e2eEmail, e2eHash, 'Smoke Test', 'editor']
      );
      console.log(`   E2E user: ${e2eEmail} (editor)`);
    }

    // ── Collections ────────────────────────────────────────────────────────
    console.log('📁 Creating collections...');
    const collectionIds: Record<string, string> = {};
    for (let i = 0; i < collections.length; i++) {
      const c = collections[i];
      const result = await client.query(
        `INSERT INTO collections (name, slug, description, icon, color, sort_order)
         VALUES ($1, $2, $3, $4, $5, $6) RETURNING id`,
        [c.name, c.slug, c.description, c.icon, c.color, i]
      );
      collectionIds[c.slug] = result.rows[0].id;
      console.log(`   ${c.icon} ${c.name} (${result.rows[0].id})`);
    }

    // ── Pages ──────────────────────────────────────────────────────────────
    console.log('📄 Creating pages...');
    const now = new Date().toISOString();

    for (const page of pages) {
      const slug = slugify(page.title);
      const collectionId = collectionIds[page.collection];

      // Insert page
      const pageResult = await client.query(
        `INSERT INTO pages (collection_id, type, title, slug, summary, mdx_source, status, published_at)
         VALUES ($1, $2, $3, $4, $5, $6, 'published', $7) RETURNING id`,
        [collectionId, page.type, page.title, slug, page.summary, page.mdx, now]
      );
      const pageId = pageResult.rows[0].id;
      console.log(`   📝 ${page.title} [${page.type}]`);

      // Insert page revision
      const plainText = stripMdx(page.mdx);
      await client.query(
        `INSERT INTO page_revisions (page_id, mdx_source, plain_text)
         VALUES ($1, $2, $3)`,
        [pageId, page.mdx, plainText]
      );

      // Insert tags
      for (const tag of page.tags) {
        await client.query(
          `INSERT INTO page_tags (page_id, tag) VALUES ($1, $2)`,
          [pageId, tag]
        );
      }

      // Insert chunks with FTS
      const chunks = splitIntoChunks(page.mdx);
      for (const chunk of chunks) {
        await client.query(
          `INSERT INTO chunks (page_id, anchor_id, heading_path, content, content_type, fts)
           VALUES ($1, $2, $3, $4, 'markdown', to_tsvector('english', $4))`,
          [pageId, slugify(chunk.heading), [chunk.heading], chunk.content]
        );
      }
    }

    await client.query('COMMIT');

    // ── Summary ────────────────────────────────────────────────────────────
    console.log('\n✅ Seed complete! Summary:');
    const counts = await Promise.all([
      pool.query('SELECT count(*) FROM users'),
      pool.query('SELECT count(*) FROM collections'),
      pool.query('SELECT count(*) FROM pages'),
      pool.query('SELECT count(*) FROM page_revisions'),
      pool.query('SELECT count(*) FROM chunks'),
      pool.query('SELECT count(*) FROM page_tags'),
    ]);
    console.log(`   Users:      ${counts[0].rows[0].count}`);
    console.log(`   Collections: ${counts[1].rows[0].count}`);
    console.log(`   Pages:       ${counts[2].rows[0].count}`);
    console.log(`   Revisions:   ${counts[3].rows[0].count}`);
    console.log(`   Chunks:      ${counts[4].rows[0].count}`);
    console.log(`   Tags:        ${counts[5].rows[0].count}`);

  } catch (err) {
    await client.query('ROLLBACK');
    console.error('❌ Seed failed:', err);
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

seed().catch(() => process.exit(1));
